name: Build and deploy site

on:
  push:
    branches:
      - main
      - master
    paths:
      - "assets/**"
      - "_data/**"
      - "_includes/**"
      - "_layouts/**"
      - "_pages/**"
      - "_projects/**"
      - "_sass/**"
      - ".github/workflows/deploy.yml"
      - "_config.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "README.md"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true

      - name: Build
        env:
          JEKYLL_ENV: production
          JEKYLL_NO_BUNDLER_REQUIRE: "true"
        run: |
          bundle exec jekyll build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
